openapi: 3.0.0
info:
  title: Linux Day API
  version: 1.0.0
  description: A simple API for Linux Day celebrations
servers:
  - url: https://localhost:8080
paths:
  /greet:
    get:
      summary: Get a personalized greeting for Linux Day
      operationId: getGreeting
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A successful response with a personalized greeting
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Welcome, {name}, to LinuxDay 2024!"

  /events:
    get:
      summary: List Linux Day events
      operationId: getEvents
      responses:
        '200':
          description: Successful response
          content:
            application/json:    
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'

  /feedback:
    post:
      summary: Submit feedback for Linux Day events
      operationId: postFeedback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the person providing feedback
                message:
                  type: string
                  description: The feedback message
                  maxLength: 500
              required:
                - name
                - message
      responses:
        '201':
          description: Feedback submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Feedback received. Thank you!"
                  feedbackId:
                    type: integer
                    description: Unique identifier for the feedback submission

components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the event
        name:
          type: string
          maxLength: 255
          description: Name of the Linux Day event
        date:
          type: string
          format: date
          description: Date of the event
        location:
          type: string
          maxLength: 255
          description: Location where the event is held
        description:
          type: string
          maxLength: 1000
          description: Brief description of the event
      required:
        - name
        - date
        - location
